application: giphytags
version: webapp
runtime: python27
api_version: 1
threadsafe: true

## uncomment during development
#default_expiration: "1m"

## automatic scaling
instance_class: F1

handlers:
- url: /json/.*
  script: main.app
- url: /static
  static_dir: static
- url: /app.js
  static_files: app.js
  upload: app.js
- url: /.*
  static_files: index.html
  upload: index.html

libraries:
- name: webapp2
  version: "latest"